/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;



/**
 *
 * @author wainwetun
 */
public class SelectionJPanel extends javax.swing.JPanel {

    private boolean isTraining;
    private SentimentClassificationMainFrame parent;
    /**
     * Creates new form SelectionJPanel
     */
    public SelectionJPanel(SentimentClassificationMainFrame parent) {
        initComponents();
        this.parent = parent;
        isTraining = true;
        rbTraining.setSelected(isTraining);       
    }
    
    public boolean isTraining(){
        return isTraining;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbTraining = new javax.swing.JRadioButton();
        rbClassify = new javax.swing.JRadioButton();

        buttonGroup1.add(rbTraining);
        rbTraining.setText("Training");
        rbTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTrainingActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbClassify);
        rbClassify.setText("Classification");
        rbClassify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClassifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbTraining)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(rbClassify)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTraining)
                    .addComponent(rbClassify))
                .addGap(0, 7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTrainingActionPerformed
        // TODO add your handling code here:
        isTraining = true;
        parent.updateContent();
    }//GEN-LAST:event_rbTrainingActionPerformed

    private void rbClassifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClassifyActionPerformed
        // TODO add your handling code here:
        isTraining = false;
        parent.updateContent();
    }//GEN-LAST:event_rbClassifyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbClassify;
    private javax.swing.JRadioButton rbTraining;
    // End of variables declaration//GEN-END:variables
}
