/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classify.Classification;
import train.InformationGainCalculation;

/**
 *
 * @author wainwetun
 */
public class TrainingJPanel extends javax.swing.JPanel {

    private boolean isPositive = false;
    /**
     * Creates new form TrainingJPanel
     */
    public TrainingJPanel() {
        initComponents();
        this.setVisible(true);
        jtaResult.setEnabled(false);
        jrbNegative.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jbTrain = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaResult = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jrbPositive = new javax.swing.JRadioButton();
        jrbNegative = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaComment = new javax.swing.JTextArea();

        jbTrain.setText("Train!");
        jbTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTrainActionPerformed(evt);
            }
        });

        jtaResult.setColumns(20);
        jtaResult.setRows(5);
        jScrollPane2.setViewportView(jtaResult);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sentiment"));

        buttonGroup1.add(jrbPositive);
        jrbPositive.setText("Positive");
        jrbPositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPositiveActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbNegative);
        jrbNegative.setText("Negative");
        jrbNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNegativeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbNegative)
                    .addComponent(jrbPositive))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jrbPositive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbNegative)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jtaComment.setColumns(20);
        jtaComment.setRows(5);
        jScrollPane1.setViewportView(jtaComment);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jbTrain)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbTrain))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNegativeActionPerformed
        // TODO add your handling code here:
        isPositive = false;
    }//GEN-LAST:event_jrbNegativeActionPerformed

    private void jbTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTrainActionPerformed
        // TODO add your handling code here:
        int isPosNeg = isPositive? 1: -1;
        InformationGainCalculation cal = new InformationGainCalculation(isPosNeg);
        StringBuilder output = new StringBuilder(cal.createTable());
        Classification classify = new Classification();
        output.append("Training new comment ..");
        output.append(classify.train());
        jtaResult.setText(output.toString());
        
    }//GEN-LAST:event_jbTrainActionPerformed

    private void jrbPositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPositiveActionPerformed
        // TODO add your handling code here:
        isPositive = true;
    }//GEN-LAST:event_jrbPositiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbTrain;
    private javax.swing.JRadioButton jrbNegative;
    private javax.swing.JRadioButton jrbPositive;
    private javax.swing.JTextArea jtaComment;
    private javax.swing.JTextArea jtaResult;
    // End of variables declaration//GEN-END:variables
}
